pipeline {
    agent any

    stage('Unit Tests - Backend') {
  agent {
    docker {
      image 'snakee/golang-junit:1.21'
      args """
        -u 1000:1000 \
        -e HOME=${WORKSPACE} \
        -e XDG_CACHE_HOME=${WORKSPACE}/.cache \
        -e GOCACHE=${WORKSPACE}/.cache/go-build \
        -e GOPATH=${WORKSPACE}/go \
        -e GOMODCACHE=${WORKSPACE}/.cache/gomod
      """
    }
  }
  steps {
    dir('bugtracker-backend') {
      sh '''
        mkdir -p "$GOCACHE" "$GOMODCACHE" "$GOPATH"
        # Opcional: verificación rápida
        go env | sort
        go test -v ./...
      '''
    }
  }
}

}
